title: Online Game Tournaments Website
description: 
theme: jekyll-theme-cayman
baseurl: "/BattleshipTournament"
# Optional settings
# Optional: Set the permalink style
permalink: pretty
# Optional: Set the markdown processor
markdown: kramdown
